export const AUTH_STATE_LOADING = 'AUTH_STATE_LAODING';
export const AUTH_STATE_FAILED = 'AUTH_STATE_FAILED';
export const AUTH_STATE_LOGOUT = 'AUTH_STATE_LOGOUT';
export const AUTH_STATE_UPDATE = 'AUTH_STATE_UPDATE';

export const FILE_STATE_LOADING = 'FILE_STATE_LOADING';
export const FILE_STATE_FAILED = 'FILE_STATE_FAILED';
export const FILE_STATE_ADD = 'FILE_STATE_ADD';
export const FILE_STATE_UPDATE = 'FILE_STATE_UPDATE';
