export const AUTH_STATE_LOADING = 'AUTH_STATE_LAODING';
export const AUTH_STATE_FAILED = 'AUTH_STATE_FAILED';
export const AUTH_STATE_LOGOUT = 'AUTH_STATE_LOGOUT';
export const AUTH_STATE_UPDATE = 'AUTH_STATE_UPDATE';

export const FILE_STATE_LOADING = 'FILE_STATE_LOADING';
export const FILE_STATE_FAILED = 'FILE_STATE_FAILED';
export const FILE_STATE_ADD_FILES = 'FILE_STATE_ADD_FILES';
export const FILE_STATE_UPDATE_FILES = 'FILE_STATE_UPDATE_FILES';
export const FILE_STATE_UPDATE_CURRENT_PAGE = 'FILE_STATE_UPDATE_CURRENT_PAGE';
export const FILE_STATE_ADD_LASTEK_MAP = 'FILE_STATE_ADD_LASTEK_MAP';
export const FILE_STATE_UPDATE_LASTEK_MAP = 'FILE_STATE_UPDATE_LASTEK_MAP';
export const FILE_STATE_UPDATE_SEARCH_PARAM = 'FILE_STATE_UPDATE_SEARCH_PARAM';
export const FILE_STATE_UPDATE_START_DATE = 'FILE_STATE_UPDATE_START_DATE';
export const FILE_STATE_UPDATE_END_DATE = 'FILE_STATE_UPDATE_END_DATE';