/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:74d8f327-234a-4840-8eae-8f352ff60eb4",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_7YemcyPmb",
    "aws_user_pools_web_client_id": "7pv4meq2fl989irvbvbiu3bh31",
    "oauth": {}
};


export default awsmobile;
